# Path to sources
sonar.organization=smikey1org
sonar.projectKey=shopivo-product-service
sonar.projectName=shopivo-product-service
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.exclusions=target/**
# sonar.inclusions=

# Path to tests
sonar.tests=src/test/java

# sonar.test.exclusions=
# sonar.test.inclusions=

# Source encoding
# sonar.sourceEncoding=

# Exclusions for copy-paste detection
# sonar.cpd.exclusions=

# Python version (for python projects only)
# sonar.python.version=